### PR TITLE
DRY configuration for webant

### PR DESCRIPTION
**Pull request by boyska**

### CODE REVIEW

**Comment by ael-code** [comment]
>  'API_URL': '/api/v1',
>  'RESULTS_PER_PAGE': 30,
>  'MAX_RESULTS_PER_PAGE': 100

are still duplicated

**Comment by boyska** [comment]
ael:

> >  'API_URL': '/api/v1',
> >  'RESULTS_PER_PAGE': 30,
> >  'MAX_RESULTS_PER_PAGE': 100
> 
> are still duplicated

fixed

**Comment by ael-code** [comment]
> defaults = conf

this is not necessary. 
Anyway I think that we are loosing some of the modularization that we achieve using sub-classing pattern.

According to me the problem of duplicated configuration is not strictly related to this PR but is a bigger design problem to which I would like to dedicate some more time.

**Comment by boyska** [comment]
Ok, I'm opening https://github.com/insomnia-lab/libreant/issues/273 and closing this

**Pull request closed without merging**
